name: update-dotnet-sdk

on:
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Update .NET SDK
    runs-on: windows-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update .NET SDK
      shell: pwsh
      run: ./update-dotnet-sdk.ps1 -Channel "5.0" -GitHubToken ${{ secrets.GITHUB_TOKEN }} -UserName "github-actions[bot]" -UserEmail "github-actions[bot]@users.noreply.github.com"
